site_name: CUTLASS Notes
theme:
  name: readthedocs
docs_dir: docs_release
nav:
  - Home: index.md
  - CuTe:
    - Cute 核心概念: cute_core.md
    - Layout 布局系统: cute_layout.md
    - Tensor 张量操作: cute_tensor.md
    - Copy 操作: 
      - Copy 操作详解: cute_copy.md
      - TMA Copy 操作: cute_tma_copy.md
    - MMA 操作:
      - MMA 操作详解: cute_mma.md
      - GMMA(SM90): cute_wgmma_sm90.md
    - 实际应用示例: cute_examples.md
  - Design:
    - '遗留问题': ../docs/design/遗留问题.md
    - '设计模式':
      - '概述': ../docs/design/设计模式/设计模式.md
      - 'Layout 设计': ../docs/design/设计模式/Layout设计.md
      - 'Copy 设计': ../docs/design/设计模式/Copy设计.md
      - 'MMA 设计': ../docs/design/设计模式/MMA设计.md
      - 'TMA 设计': ../docs/design/设计模式/TMA设计.md
    - 'CuTe':
      - '概述': ../docs/design/cute/CuTe.md
      - 'Layout': ../docs/design/cute/Layout.md
      - 'Copy': ../docs/design/cute/Copy.md
      - 'Mma': ../docs/design/cute/Mma.md
      - 'Tma': ../docs/design/cute/Tma.md
