site_name: CUTLASS Notes
theme:
  name: readthedocs
docs_dir: docs_release
nav:
  - Home: index.md
  - CuTe:
    - Cute 核心概念: cute_core.md
    - Layout 布局系统: cute_layout.md
    - Tensor 张量操作: cute_tensor.md
    - Copy 操作: 
      - Copy 操作详解: cute_copy.md
      - TMA Copy 操作: cute_tma_copy.md
    - MMA 操作:
      - MMA 操作详解: cute_mma.md
      - GMMA(SM90): cute_wgmma_sm90.md
    - 实际应用示例: cute_examples.md