site_name: CUTLASS Notes
theme:
  name: readthedocs
docs_dir: docs_release
nav:
  - Home: index.md
  - CuTe:
    - Cute 核心概念: cute_core.md
    - Layout 布局系统: cute_layout.md
    - Tensor 张量操作: cute_tensor.md
    - Copy 操作详解: cute_copy.md
    - MMA 操作: cute_mma.md
    - WGMMa SM90: cute_wgmma_sm90.md
    - TMA Copy 操作: cute_tma_copy.md
    - 实际应用示例: cute_examples.md
  - Design:
    - '遗留问题': design/遗留问题.md
    - '设计模式':
      - '概述': design/设计模式/设计模式.md
      - 'C++ 特性': design/设计模式/C++ 特性.md
      - 'CopyAtom 设计模式': design/设计模式/CopyAtom 设计模式.md
      - 'CopyTraits 设计模式': design/设计模式/CopyTraits 设计模式.md
      - 'LayoutRight{} 计算': design/设计模式/LayoutRight{} 计算.md
    - 'Cute':
      - 'Core':
        - 'ArithTuple': design/cute/core/ArithTuple.md
        - 'int': design/cute/core/int.md
        - 'size(Layout)': design/cute/core/size(Layout).md
        - 'size(tuple)': design/cute/core/size(tuple).md
        - 'tensor': design/cute/core/tensor.md
        - 'Layout':
          - 'Layout Algebra': design/cute/core/layout/layout algebra.md
          - 'group_modes': design/cute/core/layout/group_modes.md
          - 'right_inverse': design/cute/core/layout/right_inverse.md
          - 'tile_to_shape': design/cute/core/layout/tile_to_shape.md
      - 'Copy':
        - '概述': design/cute/copy/copy.md
        - 'Algorithm Copy': design/cute/copy/algorithm_copy.md
        - 'Copy Policy': design/cute/copy/CopyPolicy.md
        - 'Draft RefLayout': design/cute/copy/draft_RefLayout.md
        - 'Draft TiledCopy': design/cute/copy/draft_tiledCopy.md
        - 'TMA Copy':
          - 'TmaCopy': design/cute/copy/tma copy/TmaCopy.md
          - 'TmaDesc': design/cute/copy/tma copy/TmaDesc.md
          - 'gbasis 计算': design/cute/copy/tma copy/gbasis 计算.md
          - 'make_tma_copy': design/cute/copy/tma copy/make_tma_copy.md
          - 'tma_partition': design/cute/copy/tma copy/tma_partition.md
      - 'MMA':
        - 'MMA': design/cute/mma/mma.md
      - 'Examples':
        - 'CustomCopy': design/cute/examples/CustomCopy.md
        - 'General MMA': design/cute/examples/general mma.md
        - 'Sample SM90 TMA Copy': design/cute/examples/sample_sm90_tma_copy.md
        - 'SILU': design/cute/examples/silu.md
        - 'T Chip Impl': design/cute/examples/T chip impl.md